name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-webp-lib:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-14, macos-12]
        include:
          - suffix: so
            os: ubuntu-latest
            platform: unix
            arch: x86_64
          - suffix: dylib
            os: macos-12
            platform: mac
            arch: x86_64
          - suffix: dylib
            os: macos-14
            platform: mac
            arch: aarm64
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Debug
        working-directory: ./submodules/libwebp
        run: ls -la ./
      - name: Build WebP lib
        working-directory: ./submodules/libwebp
        run: |
          ./autogen.sh
          ./configure \
          --disable-static \
          --disable-png \
          --disable-jpeg \
          --disable-tiff \
          --disable-gif \
          --disable-wic \
          --disable-libwebpdecoder \
          --disable-libwebpextras \
          --disable-libwebpmux \
          --disable-libwebpdemux \
          --disable-sdl \
          --prefix=/tmp/webp-java-imageio/
          make
          make install
      - uses: actions/upload-artifact@v4
        name: Upload WebP libs
        with:
          name: webp-imageio_${{ matrix.platform }}_${{ matrix.arch }}
          path: /tmp/webp-java-imageio/
      - name:
        run: ls -la /tmp/webp-java-imageio/
